AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: REST API with Lambda function URL

Resources:
  SampleApiDependencies:
    Type: AWS::Serverless::LayerVersion
    DeletionPolicy: Delete
    Properties:
      Description: Python packages needed for the API
      CompatibleArchitectures:
        - arm64
      CompatibleRuntimes:
        - python3.10
      ContentUri: dependencies
    Metadata:
      BuildMethod: python3.10
      BuildArchitecture: arm64

  SampleApi:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda with a function URL
      CodeUri: src
      Runtime: python3.10
      Handler: app.handler
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  Url:
    Description: API base URL
    Value: !GetAtt SampleApiUrl.FunctionUrl
